# Generated by Django 4.1.13 on 2024-03-29 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('last_changed', models.DateTimeField(blank=True, null=True)),
                ('latest_content', models.TextField()),
                ('content_dict', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'policy_name')},
            },
        ),
    ]
